language: java

sudo: false

install: true

addons:
  sonarqube: true
env:
  global:
    secure: "mvrqZ/FyEKvLzXfJFIHaR5zTp+ftapnxdMnlpVSveoz2F+HKbMT/Lq0/VClSbYTVKRlIZuo99NiVX4czUbazYltbwMOUmkN5gi8rBvWexxuQXfRuE/g9ZX+gUwdZZts0RCWNf7e7uNPFyJvFy8LC3ioa00R/DVU8r40l/IJQ8TAl1RBQFc4CeWM02PVnoXkzfc/Ey5vd8omdl6nS8+MT78GTwWXvHvQefVbD6B/zjP/CEXAq3d4azoXz3uo3qMiSMsWPgU4NOm0aZ2jyUzvukHNdFsb+ywRJtW9yO4nZO6O6DXTZtGP9sPdLg1+M1XXNF/wV8nBrEaFOWKtXKHI8Mv/vmiTHbIDIqecA2oDY8cA6GkhxQ+jbT/3JpZy2g8oJwekEnFR9dbmwx54fgkzb4CWfw3/nybbmcZgNITBFCj9n/V9NdDWkgW3nO2xeLvrKlVHEYT28CtlGk66+DEClxXiSx35P3qPZSl05/v6k3PsU+RLifADF8fFrdOGHSgLAUyRNbPhHVYp48bSDSJ104jDenO9ZNM6Y5++8Edb7F7O78YETW7MtA6/huaVaENvsmzRZzw1R27GQpxlbC4ji3SVtFjl6jxNV8NyBui8XNK+gw7TCk63gSO59OcWgpOENryLjc814U47Z3zpqj2rao/qkhPAnAZIyWbVoCnHxlGE="

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false