language: java

sudo: false

install: true

addons:
  sonarqube: true

env:
  global:
    secure: "fNO6Be2e0sWHAspWF7+581YPrHeozPpDgTid7CgD65+fXHVEF9d+10X8RdJaXli4mbR6d4yYDZvZAx3ga1TV8LVHxqRNwOltRj5V9xMtZYEe4S862EwUGyhVeFOY2i5EeZw86fHFrxBFY6FIsnDEqOPJkPkhUX2IugkxzlEC+9ModZjnQxQr9dI960jwoWQfBaGrNfkOnMw02+6DUu45pCtdLNNHRUgEGZxmDCtpe/l1qYuAE9blW+YprULj6KMwdRMNAN4RZgq8QqnY+yiHWVBk/Xy/2T9MI5Uq9klwwY8jr0KuyAHlzMw+85jKgyxDZHyOnziN2OFK8RBb1tHyoXFEYJWJTs/YNxt/SGF61HB7otu08z3xrfthwF8sxM7tNwUAU/dKsD0Caraz2N+KxVjtw5GQlEwb5tEKUCoY2D21L4iySe6/XWl7PI+zbm7DP+oIJaEtjC6eSfbcaTRqQnrVLNm6XF5gC6Yb8QTHMr416iBfiTXj82FvLUS/tK31ZH7d5TqUgqJEszMFw3Kp03IQxw+2UEUYgbW7yLIm47R4I7Pc/Uxot+luSGtChH78ofWH1sTjq4lmhdqtfOzVo1SV7GU/rd/d+F/R3uNUwXEucAXHobMgidE0qD8QTlIy/PLGtVFZCsKbA8IEnXDqNeI2MXz57uNITy5yA0wy7Vw="

jdk:
- oraclejdk8

script:
- ./gradlew sonarqube

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle

notifications:
  email: false
