spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      maxPollRecords: 10
  mvc.servlet.load-on-startup: 1

  jackson:
    serialization:
      fail_on_empty_beans: false
      indent_output: true
      write_dates_as_timestamps: false

server:
  error.whitelabel.enabled: false